logging:
    level:
        org:
            springframework:
                security: debug
spring:
    application:
        name: Backend
external:
    api:
        key: AIzaSyA2DL6D565P86EeuOZwe3n1en_dXNkH9yk
    cse:
        key: c0b82d25f184041a2
security:
    jwt:
        secret:
            key: 954BDC4C4A99784B5B229A312DF4DDJDJ9393993JDJDJ399393JDJDJ399393
        issuer: Job Bazaar API Management
